const products = [
  {
    id: 1,
    title: 'acre-of-farmland',
    price: 0.5,
    image: './images/acre-of-farmland.jpg',
  },
  {
    id: 2,
    title: 'air-jordans',
    price: 125,
    image: './images/air-jordans.jpg',
  },
  {
    id: 199,
    title: 'airpods',
    price: 400,
    image: './images/airpods.jpg',
  },
  {
    id: 4,
    title: 'amazon-echo',
    price: 99,
    image: './images/amazon-echo.jpg',
  },
  {
    id: 5,
    title: 'apache-helicopter',
    price: 31000000,
    image: './images/apache-helicopter.jpg',
  },
  {
    id: 6,
    title: 'auto-rickshaw',
    price: 2300,
    image: './images/auto-rickshaw.jpg',
  },
  {
    id: 7,
    title: 'auto-rickshaw',
    price: 3500,
    image: './images/auto-rickshaw.jpg',
  },
  {
    id: 8,
    title: 'big-mac',
    price: 3,
    image: './images/big-mac.jpg',
  },
  {
    id: 9,
    title: 'bike',
    price: 800,
    image: './images/bike.jpg',
  },
  {
    id: 10,
    title: 'boeing-747',
    price: 40000000,
    image: './images/boeing-747.jpg',
  },
  {
    id: 11,
    title: 'book',
    price: 10,
    image: './images/book.jpg',
  },
  {
    id: 12,
    title: 'coca-cola',
    price: 5,
    image: './images/coca-cola-pack.jpg',
  },
  {
    id: 13,
    title: 'cruise-ship',
    price: 99900000,
    image: './images/cruise-ship.jpg',
  },
  {
    id: 14,
    title: 'handbag',
    price: 555,
    image: './images/designer-handbag.jpg',
  },
  {
    id: 15,
    title: 'diamond-ring',
    price: 1250,
    image: './images/diamond-ring.jpg',
  },
  {
    id: 16,
    title: 'Tesla',
    price: 55000,
    image: './images/tesla.jpg',
  },

  {
    id: 17,
    title: 'drone',
    price: 575,
    image: './images/drone.jpg',
  },
  {
    id: 18,
    title: 'ferrari',
    price: 2500000,
    image: './images/ferrari.jpg',
  },
  {
    id: 19,
    title: 'flip-flops',
    price: 4,
    image: './images/flip-flops.jpg',
  },
  {
    id: 20,
    title: 'ford-f-150',
    price: 15000000,
    image: './images/ford-f-150.jpg',
  },
  {
    id: 21,
    title: 'formula-1-car',
    price: 875000,
    image: './images/formula-1-car.jpg',
  },
  {
    id: 22,
    title: 'gaming-console',
    price: 45,
    image: './images/gaming-console.jpg',
  },
  {
    id: 23,
    title: 'gold-bar',
    price: 500000,
    image: './images/gold-bar.jpg',
  },
  {
    id: 24,
    title: 'horse',
    price: 1000,
    image: './images/horse.jpg',
  },
  {
    id: 25,
    title: 'hot-tub',
    price: 1000,
    image: './images/hot-tub.jpg',
  },
  {
    id: 26,
    title: 'jet-ski',
    price: 1450,
    image: './images/jet-ski.jpg',
  },
  {
    id: 27,
    title: 'kitten',
    price: 55,
    image: './images/kitten.jpg',
  },
  {
    id: 28,
    title: 'lobster-dinner',
    price: 78,
    image: './images/lobster-dinner.jpg',
  },
  {
    id: 29,
    title: 'luxury-wine',
    price: 45,
    image: './images/luxury-wine.jpg',
  },
  {
    id: 30,
    title: 'm1-abrams',
    price: 600000,
    image: './images/m1-abrams.jpg',
  },
  {
    id: 31,
    title: 'make-a-movie',
    price: 1500000,
    image: './images/make-a-movie.jpg',
  },
  {
    id: 32,
    title: 'mansion',
    price: 5000000,
    image: './images/mansion.jpg',
  },
  {
    id: 33,
    title: 'mcdonalds-franchise',
    price: 5400000,
    image: './images/mcdonalds-franchise.jpg',
  },
  {
    id: 34,
    title: 'mona-lisa',
    price: 90000000,
    image: './images/mona-lisa.jpg',
  },
  {
    id: 35,
    title: 'money-bag',
    price: 50000,
    image: './images/money-bag-dollar-color-icon.svg',
  },
  {
    id: 36,
    title: 'monster-truck',
    price: 500000,
    image: './images/monster-truck.jpg',
  },
  {
    id: 37,
    title: 'movie-ticket',
    price: 44,
    image: './images/movie-ticket.jpg',
  },
  {
    id: 38,
    title: 'nba-team',
    price: 3000000,
    image: './images/nba-team.jpg',
  },
  {
    id: 39,
    title: 'puppy',
    price: 34,
    image: './images/puppy.jpg',
  },
  {
    id: 40,
    title: 'single-family-home',
    price: 5000000,
    image: './images/single-family-home.jpg',
  },
  {
    id: 41,
    title: 'smartphone',
    price: 567,
    image: './images/smartphone.jpg',
  },
  {
    id: 42,
    title: 'superbowl-ad',
    price: 580000,
    image: './images/superbowl-ad.jpg',
  },
]
export default products